version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm prune --production
      - npm run build
      - npm install -g serverless
  pre_build:
    commands:
      - npm install cypress
      - cypress install
      - npm run dev &> /dev/null
      - npm run test:e2e:ci
  build:
    commands:
      - serverless deploy -s test