version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm prune --production
      - npm run build
      - npm install -g serverless
  build:
    commands:
      - serverless deploy -s test