service: coronavirus-here-to-help-frontend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: ${opt:stage}
  apiGateway:
    shouldStartNameWithService: true

package:
  individually: true
  exclude:
    - ./**

functions:
  coronavirus-here-to-help-frontend:
    name: ${self:service}-${self:provider.stage}
    handler: src/lambda.handler
    package:
      include:
        - auth-groups.json
        - src/lambda.js
        - next.config.js
        - public/**
        - build/_next/**
        - node_modules/**
    events:
      - http:
          path: /{any+}
          method: get
    vpc:
      securityGroupIds: ${self:custom.securityGroups.${self:provider.stage}}
      subnetIds: ${self:custom.subnets.${self:provider.stage}}
resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
#          Aliases:
#            - ${self:custom.aliases.${self:provider.stage}}
          PriceClass: PriceClass_100
#          ViewerCertificate:
#            AcmCertificateArn: ${self:custom.certificate-arn.${self:provider.stage}}
#            MinimumProtocolVersion: TLSv1.2_2018
#            SslSupportMethod: sni-only
          DefaultCacheBehavior:
            TargetOriginId: ${self:service}-${self:provider.stage}-custom-origin
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
          Enabled: true
          Origins:
            - Id: ${self:service}-${self:provider.stage}-custom-origin
              DomainName: ${self:custom.domain-name}
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only

custom:
  domain-name:
    Fn::Join:
      - '.'
      - - Ref: ApiGatewayRestApi
        - execute-api
        - eu-west-2
        - amazonaws.com
  aliases:
    development: here-to-help-development.hackney.gov.uk
    production: here-to-help.hackney.gov.uk
  certificate-arn:
#    staging: arn:aws:acm:us-east-1:*:certificate/*
#    production: arn:aws:acm:us-east-1:*:certificate/*
  securityGroups:
    development:
      - sg-0ebfce25888807a37
    production:
 #     - sg-*
  subnets:
    development:
      - subnet-e7d40eab
    production:
#      - subnet-*